config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :product_imports, only: [:index] do
      collection do
        delete :reset
        get :sample_import
        post :sample_csv_import
        post :user_csv_import
        get :download_sample_csv
        post :shopify_csv_import
        get :download_sample_shopify_export_csv
      end
    end
    resources :order_imports, only: [:index] do
      collection do
        delete :reset
        get :sample_import
        post :sample_csv_import
        post :user_csv_import
        get :download_sample_csv
      end
    end
    resources :user_imports, only: [:index] do
      collection do
        delete :reset
        get :sample_import
        post :sample_csv_import
        post :user_csv_import
        get :download_sample_csv
      end
    end
  end
end

app/models/spree/app_configuration_decorator.rb
Spree::AppConfiguration.class_eval do
  preference :allow_datashift_reset, :boolean, default: false
end

app/models/spree/user_decorator.rb
Spree::User.class_eval do

  ### SCOPES ###
  scope :non_admins, -> { where.not(id: admin.pluck(:id)) }

end

app/controllers/spree/admin/order_imports_controller.rb
class Spree::Admin::OrderImportsController < Spree::Admin::BaseController

  before_action :ensure_valid_file, only: :user_csv_import

  def index
    @csv_table = CSV.open(DATASHIFT_CSV_FILES[:sample_order_file], headers: true).read
  end

  def reset
    flash[:success] = Spree.t(:orders, scope: [:datashift_import, :reset_message], order_numbers: Spree::DataResetService.new.reset_orders)
    redirect_to admin_order_imports_path
  end

  def sample_import
  end

  def download_sample_csv
    send_file DATASHIFT_CSV_FILES[:sample_order_file]
  end

  def sample_csv_import
    begin
      loader = DataShift::SpreeEcom::ShopifyOrderLoader.new(DATASHIFT_CSV_FILES[:sample_order_file], { verbose: true })
      loader.run
      flash[:success] = Spree.t(:successfull_import, scope: :datashift_import, resource: Spree::Order.name.demodulize)
    rescue => e
      flash[:error] = e.message
    end
    redirect_to admin_order_imports_path
  end

  def user_csv_import
    begin
      loader = DataShift::SpreeEcom::ShopifyOrderLoader.new(params[:csv_file].path, { verbose: true })
      loader.run
      flash[:success] = Spree.t(:successfull_import, scope: :datashift_import, resource: Spree::Order.name.demodulize)
    rescue => e
      flash[:error] = e.message
    end
    redirect_to admin_order_imports_path
  end

  private

    def ensure_valid_file
      unless params[:csv_file].try(:respond_to?, :path)
        flash[:error] = Spree.t(:file_invalid_error, scope: :datashift_import)
        redirect_to admin_order_imports_path
      end
    end

end

app/controllers/spree/admin/product_imports_controller.rb
class Spree::Admin::ProductImportsController < Spree::Admin::BaseController

  before_action :ensure_valid_file, only: [:user_csv_import, :shopify_csv_import]
  before_action :set_loader_options, only: [:sample_csv_import, :user_csv_import]

  def index
    @csv_table = CSV.open(DATASHIFT_CSV_FILES[:sample_product_file], headers: true).read if File.exists? DATASHIFT_CSV_FILES[:sample_product_file]
  end

  def reset
    flash[:success] = Spree::DataResetService.new.reset_products
    redirect_to admin_product_imports_path
  end

  def sample_import
  end

  def download_sample_csv
    send_file DATASHIFT_CSV_FILES[:sample_product_file]
  end

  def sample_csv_import
    begin
      loader = DataShift::SpreeEcom::ProductLoader.new(DATASHIFT_CSV_FILES[:sample_product_file], @options)
      loader.run
      flash[:success] = Spree.t(:successfull_import, scope: :datashift_import, resource: Spree::Product.name.demodulize)
    rescue => e
      flash[:error] = e.message
    end
    redirect_to admin_product_imports_path
  end

  def user_csv_import
    begin
      loader = DataShift::SpreeEcom::ProductLoader.new(params[:csv_file].path, @options)
      loader.run
      flash[:success] = Spree.t(:successfull_import, scope: :datashift_import, resource: Spree::Product.name.demodulize)
    rescue => e
      flash[:error] = e.message
    end
    redirect_to admin_product_imports_path
  end

  def download_sample_shopify_export_csv
    send_file DATASHIFT_CSV_FILES[:shopify_products_export_file]
  end

  def shopify_csv_import
    begin
      transformer = DataShift::SpreeEcom::ShopifyProductTransform.new(params[:csv_file].path)
      send_data transformer.to_csv,
        type: 'text/csv; charset=iso-8859-1; header=present',
        filename: 'shopify_to_spree_mapper.csv'
    rescue => e
      flash[:error] = e.message
      redirect_to sample_import_admin_product_imports_path
    end
  end

  private
    def ensure_valid_file
      unless params[:csv_file].try(:respond_to?, :path)
        flash[:error] = Spree.t(:file_invalid_error, scope: :datashift_import)
        redirect_to admin_product_imports_path
      end
    end

    def set_loader_options
      @options ||= {}
      @options[:mandatory] = PRODUCT_MANDATORY_FIELDS
    end
end

app/controllers/spree/admin/user_imports_controller.rb
class Spree::Admin::UserImportsController < Spree::Admin::BaseController

  before_action :fetch_non_admins, only: [:index, :sample_import, :reset]
  before_action :ensure_valid_file, only: :user_csv_import

  def index
    @csv_table = CSV.open(DATASHIFT_CSV_FILES[:sample_user_file], headers: true).read
  end

  def reset
    flash[:success] = Spree::DataResetService.new.reset_users_with_orders(@non_admins)
    redirect_to admin_user_imports_path
  end

  def sample_import
  end

  def download_sample_csv
    send_file DATASHIFT_CSV_FILES[:sample_user_file]
  end

  def sample_csv_import
    begin
      loader = DataShift::SpreeEcom::ShopifyCustomerLoader.new(DATASHIFT_CSV_FILES[:sample_user_file], { verbose: true, address_type: params[:address_type] })
      loader.run
      flash[:success] = Spree.t(:successfull_import, scope: :datashift_import, resource: Spree.user_class.name.demodulize)
    rescue => e
      flash[:error] = e.message
    end
    redirect_to admin_user_imports_path
  end

  def user_csv_import
    begin
      loader = DataShift::SpreeEcom::ShopifyCustomerLoader.new(params[:csv_file].path, { verbose: true, address_type: params[:address_type] })
      loader.run
      flash[:success] = Spree.t(:successfull_import, scope: :datashift_import, resource: Spree.user_class.name.demodulize)
    rescue => e
      flash[:error] = e.message
    end
    redirect_to admin_user_imports_path
  end

  private

    def ensure_valid_file
      unless params[:csv_file].try(:respond_to?, :path)
        flash[:error] = Spree.t(:file_invalid_error, scope: :datashift_import)
        redirect_to admin_user_imports_path
      end
    end

    def fetch_non_admins
      @non_admins = Spree.user_class.non_admins
      @non_admin_user_count = @non_admins.count
    end

end

app/helpers/spree/admin/navigation_helper_decorator.rb
Spree::Admin::NavigationHelper.class_eval do
  #Override: Add disable_with option to prevent multiple request on consecutive clicks
  def button(text, icon_name = nil, button_type = 'submit', options={})
    if icon_name
      icon = content_tag(:span, '', class: "icon icon-#{icon_name}")
      text.insert(0, icon + ' ')
    end
    button_tag(text.html_safe, options.merge(type: button_type, class: "btn btn-primary #{options[:class]}", 'data-disable-with' => "#{ Spree.t(:saving) }..."))
  end
end

app/views/spree/admin/order_imports/_import_form.html.erb
<div class="panel-body">
  <div class="row">
    <div class="col-md-6">
      <ol>
        <li>Choose a CSV by clicking 'choose file' button.</li>
        <li>Make sure your CSV has headers as present in sample CSV.</li>
        <li>Click on Import.</li>
        <br>
      </ol>
    </div>
    <div class="col-md-6">
      <div class="panel panel-info">
        <div class="panel-heading">Import CSV</div>
        <div class="panel-body">
          <%= form_tag(user_csv_import_admin_order_imports_path, multipart: true, class: 'form-horizontal') do %>
            <fieldset>
              <div class="form-group">
                <%= label_tag :csv_file, Spree.t(:filename), class: 'col-md-2 control-label', required: true   %>
                <div class="col-md-10">
                  <%= file_field_tag :csv_file, accept: 'text/csv' %>
                </div>
              </div>
              <div class="form-group">
                <div class="col-md-10 col-md-offset-1">
                  <%= submit_tag Spree.t(:import, scope: :datashift_import), class: 'btn btn-primary' %>
                </div>
              </div>
            </fieldset>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/spree/admin/order_imports/_order_imports_sidebar_tabs.html.erb
<ul class="nav nav-pills nav-stacked" data-hook="admin_product_tabs">
  <%= content_tag :li, class: 'active' do %>
    <%= link_to Spree.t(:details), 'javascript:void(0)' %>
  <% end %>
  <%= content_tag :li do %>
    <%= link_to Spree.t(:verify_orders, scope: [:datashift_import, :import_headings, :order_import_headings], order_count: Spree::Order.count), admin_orders_path %>
  <% end %>
</ul>

app/views/spree/admin/order_imports/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:order_import, scope: [:datashift_import, :import_headings, :order_import_headings]) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:clear_orders, scope: [:datashift_import, :import_headings, :order_import_headings]), reset_admin_order_imports_path, { class: "btn-success", icon: 'trash', method: :delete, data: { confirm: Spree.t(:order_reset_confirmation, scope: [:datashift_import, :import_headings, :order_import_headings]) } } if Spree::Config.allow_datashift_reset %>
  <%= button_link_to Spree.t(:import_orders, scope: [:datashift_import, :import_headings, :order_import_headings]), sample_import_admin_order_imports_path, { class: "btn-success", icon: 'add' } %>
<% end %>

<% content_for :sidebar do %>
  <%= render 'order_imports_sidebar_tabs' %>
<% end %>


<% if Spree::Config.allow_datashift_reset %>
  <div>
    <strong>Note - </strong>In development mode, For better verification we recommend you to first <%= link_to Spree.t(:clear_order_data, scope: [:datashift_import, :import_headings, :order_import_headings]), reset_admin_order_imports_path, method: :delete, data: { confirm: Spree.t(:order_reset_confirmation, scope: [:datashift_import, :import_headings, :order_import_headings]) } %> and then try to <%= link_to Spree.t(:import_orders, scope: [:datashift_import, :import_headings, :order_import_headings]), sample_import_admin_order_imports_path %>.
  </div>

  <br><br>
<% end %>

<% if @csv_table %>
  <h3 class="text-center">Sample CSV Data</h3>
  <%= render 'spree/admin/shared/sample_csv_data', csv_table: @csv_table %>
<% end %>

app/views/spree/admin/order_imports/sample_import.html.erb
<% content_for :page_title do %>
  <%= link_to Spree.t(:order_import, scope: [:datashift_import, :import_headings, :order_import_headings]), admin_order_imports_url %> /
  <%= Spree.t(:import, scope: :datashift_import) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:download_sample_file, scope: :datashift_import), download_sample_csv_admin_order_imports_path, { class: "btn-success", icon: 'download-alt' } %>
<% end %>


<% if Spree::Order.count > 0 && Spree::Config.allow_datashift_reset %>
  <div class="row">
    <strong>Note - </strong>In development mode, For better verification we recommend you to first <%= link_to Spree.t(:clear_order_data, scope: [:datashift_import, :import_headings, :order_import_headings]), reset_admin_order_imports_path, method: :delete, data: { confirm: Spree.t(:order_reset_confirmation, scope: [:datashift_import, :import_headings, :order_import_headings]) } %> and then try to <%= link_to Spree.t(:import_orders, scope: [:datashift_import, :import_headings, :order_import_headings]), sample_import_admin_order_imports_path %>.
  </div>
<% end %>

<div class="row">
  <h3 class='text-center'><b>Instructions</b></h3>
  <div class="panel panel-default">
    <div class="panel-heading">a) If you are importing using CSV file</div>
    <%= render 'import_form' %>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">b) If you are importing using sample data</div>
    <div class="panel-body">
      <div class="row">
        <div class="col-md-6">
          <ol>
            <li>Click on 'Import with Sample data' and verify the imported data</li>
            <li>You can also download the sample file and customized it according to your need and upload it again using first step</li>
            <br>
          </ol>
        </div>
        <div class="col-md-6">
          <div class="panel panel-info">
            <div class="panel-heading">Sample Import</div>
            <div class="panel-body">
              <div>
                <%= link_to Spree.t(:import_with_sample_data, scope: [:datashift_import, :import_headings, :order_import_headings]), sample_csv_import_admin_order_imports_path, method: :post, data: { confirm: Spree.t(:are_you_sure) }, class: 'btn btn-default' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/spree/admin/product_imports/_import_form.html.erb
<div class="panel-body">
  <div class="row">
    <div class="col-md-6">
      <ol>
        <li>Choose a CSV by clicking 'choose file' button.</li>
        <li>Make sure your CSV has headers as present in sample CSV.</li>
        <li>Click on Import.</li>
        <br>
      </ol>
    </div>
    <div class="col-md-6">
      <div class="panel panel-info">
        <div class="panel-heading">Import CSV</div>
        <div class="panel-body">
          <%= form_tag(user_csv_import_admin_product_imports_path, multipart: true, class: 'form-horizontal') do %>
            <fieldset>
              <div class="form-group">
                <%= label_tag :csv_file, Spree.t(:filename), class: 'col-md-2 control-label', required: true   %>
                <div class="col-md-10">
                  <%= file_field_tag :csv_file, accept: 'text/csv' %>
                </div>
              </div>
              <div class="form-group">
                <div class="col-md-10 col-md-offset-1">
                  <%= submit_tag Spree.t(:import, scope: :datashift_import), class: 'btn btn-primary' %>
                </div>
              </div>
            </fieldset>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/spree/admin/product_imports/_transform_form.html.erb
<div class="panel-body">
  <div class="row">
    <div class="col-md-6">
      <ol>
        <li>Choose a Shopify Export CSV file by clicking 'choose file' button.</li>
        <li>Click on 'Transform to Spree Format'.</li>
        <li>Now upload the transformed CSV file using STEP 'a'</li>
        <li>You can also download 'Sample Shopify Export file' and customize it and process is using STEP 'a' and 'c'</li>
        <br>
      </ol>
    </div>
    <div class="col-md-6">
      <div class="panel panel-info">
        <div class="panel-heading">Transform Shopify CSV file</div>
        <div class="panel-body">
          <%= form_tag(shopify_csv_import_admin_product_imports_path, multipart: true, class: 'form-horizontal') do %>
            <fieldset>
              <div class="form-group">
                <%= label_tag :csv_file, Spree.t(:filename), class: 'col-md-2 control-label', required: true   %>
                <div class="col-md-10">
                  <%= file_field_tag :csv_file, accept: 'text/csv' %>
                </div>
              </div>
              <div class="form-group">
                <div class="col-md-10 col-md-offset-1">
                  <%= submit_tag Spree.t(:transform_to_spree_format, scope: [:datashift_import, :import_headings, :product_import_headings]), class: 'btn btn-primary' %>
                </div>
              </div>
            </fieldset>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/spree/admin/product_imports/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:product_import, scope: [:datashift_import, :import_headings, :product_import_headings]) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:clear_products, scope: [:datashift_import, :import_headings, :product_import_headings]), reset_admin_product_imports_path, { class: "btn-success", icon: 'trash', method: :delete, data: { confirm: Spree.t(:product_reset_confirmation, scope: [:datashift_import, :import_headings, :product_import_headings]) } } if Spree::Config.allow_datashift_reset %>
  <%= button_link_to Spree.t(:import_products, scope: [:datashift_import, :import_headings, :product_import_headings]), sample_import_admin_product_imports_path, { class: "btn-success", icon: 'add' } %>
<% end %>

<% if Spree::Config.allow_datashift_reset %>
  <div>
    <strong>Note - </strong>In development mode, For better verification we recommend you to first <%= link_to Spree.t(:clear_product_data, scope: [:datashift_import, :import_headings, :product_import_headings]), reset_admin_product_imports_path, method: :delete, data: { confirm: Spree.t(:product_reset_confirmation, scope: [:datashift_import, :import_headings, :product_import_headings]) } %> and then try to <%= link_to Spree.t(:import_products, scope: [:datashift_import, :import_headings, :product_import_headings]), sample_import_admin_product_imports_path %>.
  </div>

  <br><br>
<% end %>


<% content_for :sidebar do %>
  <%= render 'product_import_sidebar_tabs' %>
<% end %>

<% if @csv_table %>
  <h3 class="text-center">Sample CSV Data</h3>
  <%= render 'spree/admin/shared/sample_csv_data', csv_table: @csv_table %>
<% end %>

app/views/spree/admin/product_imports/sample_import.html.erb
<% content_for :page_title do %>
  <%= link_to Spree.t(:product_import, scope: [:datashift_import, :import_headings, :product_import_headings]), admin_product_imports_url %> /
  <%= Spree.t(:import, scope: :datashift_import) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:download_sample_file, scope: :datashift_import), download_sample_csv_admin_product_imports_path, { class: "btn-success", icon: 'download-alt' } %>
  <%= button_link_to Spree.t(:download_shopify_file, scope: :datashift_import), download_sample_shopify_export_csv_admin_product_imports_path, { class: "btn-success", icon: 'download-alt' } %>
<% end %>

<% if Spree::Product.count > 0 && Spree::Config.allow_datashift_reset %>
  <div class="row">
    <strong>Note - </strong>In development mode, For better verification we recommend you to first <%= link_to Spree.t(:clear_product_data, scope: [:datashift_import, :import_headings, :product_import_headings]), reset_admin_product_imports_path, method: :delete, data: { confirm: Spree.t(:product_reset_confirmation, scope: [:datashift_import, :import_headings, :product_import_headings]) } %> and then try to <%= link_to Spree.t(:import_products, scope: [:datashift_import, :import_headings, :product_import_headings]), sample_import_admin_product_imports_path %>.
  </div>
<% end %>



<div class="row">
  <h3 class='text-center'><b>Instructions</b></h3>
  <div class="panel panel-default">
    <div class="panel-heading">a) If you are importing using CSV file</div>
    <%= render 'import_form' %>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">b) If you are importing using sample data.</div>

    <div class="panel-body">
      <div class='row'>
        <div class="col-md-6">
          <ol>
            <li>Click on 'Import with Sample data' and verify the imported data.</li>
            <li>You can also download the sample file and customized it according to your need and upload it again using STEP 'a'.</li>
            <br>
          </ol>
        </div>

        <div class="col-md-6">
          <div class="panel panel-info">
            <div class="panel-heading">Sample Import</div>
            <div class="panel-body">
              <div>
                <%= link_to Spree.t(:import_with_sample_data, scope: [:datashift_import, :import_headings, :product_import_headings]), sample_csv_import_admin_product_imports_path, method: :post, data: { confirm: Spree.t(:are_you_sure) }, class: 'btn btn-default' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">c) If you are importing using Shopify Export file</div>
    <%= render 'transform_form' %>
  </div>

</div>

app/views/spree/admin/shared/_import_side_menu.html.erb
<% if can?(:admin, Spree::Admin::OrderImportsController) || can?(:admin, Spree::Admin::ProductImportsController) || can?(:admin, Spree::Admin::UserImportsController) %>
  <ul class="nav nav-sidebar border-bottom">
    <%= main_menu_tree Spree.t(:imports, scope: :datashift_import), icon: "download-alt", sub_menu: "import", url: "#sidebar-import" %>
  </ul>
<% end %>

app/views/spree/admin/shared/_sample_csv_data.html.erb
<div class='table-responsive'>
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <% csv_table.headers.each do |header| %>
          <th><%= header %></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% csv_table.each do |row| %>
        <tr>
          <% row.each do |element| %>
            <td><%= element[1] %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/spree/admin/user_imports/_import_form.html.erb
<div class="panel-body">
  <div class="row">
    <div class="col-md-6">

      <ol>
        <li>Choose a CSV by clicking 'choose file' button.</li>
        <li>Make sure your CSV has headers as present in sample CSV.</li>
        <li>Select appropriate address type by selection the radio button.</li>
        <li>Click on Import.</li>
        <br>
      </ol>
    </div>
    <div class="col-md-6">
      <div class="panel panel-info">
        <div class="panel-heading">Import CSV</div>
        <div class="panel-body">
          <%= form_tag(user_csv_import_admin_user_imports_path, multipart: true, class: 'form-horizontal') do %>
            <fieldset>
              <div class="form-group">
                <%= label_tag :csv_file, Spree.t(:filename), class: 'col-md-2 control-label', required: true   %>
                <div class="col-md-10">
                  <%= file_field_tag :csv_file, accept: 'text/csv' %>
                </div>
              </div>

              <div class="form-group">
                <label class="col-md-2 control-label">Address Type</label>
                <div class="col-md-10">
                  <div class="radio">
                    <label>
                      <%= radio_button_tag 'address_type', 'ship_address', true %>
                      <%= Spree.t(:ship_address) %>
                    </label>
                  </div>
                  <div class="radio">
                    <label>
                      <%= radio_button_tag 'address_type', 'bill_address' %>
                      <%= Spree.t(:bil_address) %>
                    </label>
                  </div>
                </div>
              </div>
              <div class="form-group">
                <div class="col-md-10 col-md-offset-1">
                  <%= submit_tag Spree.t(:import, scope: :datashift_import), class: 'btn btn-primary' %>
                </div>
              </div>
            </fieldset>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/spree/admin/user_imports/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:user_import, scope: [:datashift_import, :import_headings, :user_import_headings]) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:clear_users, scope: [:datashift_import, :import_headings, :user_import_headings]), reset_admin_user_imports_path, { class: "btn-success", icon: 'trash', method: :delete, data: { confirm: Spree.t(:user_reset_confirmation, scope: [:datashift_import, :import_headings, :user_import_headings]) } } if Spree::Config.allow_datashift_reset %>
  <%= button_link_to Spree.t(:import_users, scope: [:datashift_import, :import_headings, :user_import_headings]), sample_import_admin_user_imports_path, { class: "btn-success", icon: 'add' } %>
<% end %>

<% content_for :sidebar do %>
  <%= render 'user_import_sidebar_tabs' %>
<% end %>

<% if Spree::Config.allow_datashift_reset %>
  <div><strong>Note - </strong>In development mode, For better verification we recommend you to first <%= link_to Spree.t(:clear_user_data, scope: [:datashift_import, :import_headings, :user_import_headings]), reset_admin_user_imports_path, data: { confirm: Spree.t(:user_reset_confirmation, scope: [:datashift_import, :import_headings, :user_import_headings]) }, method: :delete %> and then try to <%= link_to Spree.t(:import_users, scope: [:datashift_import, :import_headings, :user_import_headings]), sample_import_admin_user_imports_path %>.</div>

  <br>
  <br>
<% end %>

<% if @csv_table %>
  <h3 class="text-center">Sample CSV Data</h3>
  <%= render 'spree/admin/shared/sample_csv_data', csv_table: @csv_table %>
<% end %>

app/views/spree/admin/user_imports/sample_import.html.erb
<% content_for :page_title do %>
  <%= link_to Spree.t(:user_import, scope: [:datashift_import, :import_headings, :user_import_headings]), admin_user_imports_url %> /
  <%= Spree.t(:import, scope: :datashift_import) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:download_sample_file, scope: :datashift_import), download_sample_csv_admin_user_imports_path, { class: "btn-success", icon: 'download-alt' } %>
<% end %>

<% if @non_admin_user_count > 0 && Spree::Config.allow_datashift_reset %>
  <div class="row">
    <strong>Note - </strong>In development mode, For better verification we recommend you to first <%= link_to Spree.t(:clear_user_data, scope: [:datashift_import, :import_headings, :user_import_headings]), reset_admin_user_imports_path, method: :delete, data: { confirm: Spree.t(:user_reset_confirmation, scope: [:datashift_import, :import_headings, :user_import_headings]) } %> and then try to <%= link_to Spree.t(:import_users, scope: [:datashift_import, :import_headings, :user_import_headings]), sample_import_admin_user_imports_path %>.
  </div>
<% end %>

<div class="row">
  <h3 class='text-center'><b>Instructions</b></h3>
  <div class="panel panel-default">
    <div class="panel-heading">a) If you are importing using CSV file</div>
    <%= render 'import_form' %>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">b) If you are importing using sample data</div>
    <div class="panel-body">
      <div class="row">
        <div class="col-md-6">
          <ol>
            <li>Click on 'Import with Sample data using bill_address' if you want to import sample data and use address as bill_address.</li>
            <li>Click on 'Import with Sample data using ship_address' if you want to import sample data and use address as ship_address.</li>
            <li>You can also download the sample file and customized it according to your need and upload it again using first step</li>
            <br>
          </ol>
        </div>
        <div class="col-md-6">
          <div class="panel panel-info">
            <div class="panel-heading">Sample Import</div>
            <div class="panel-body">
              <div>
                <%= link_to Spree.t(:import_with_bill_address, scope: [:datashift_import, :import_headings, :user_import_headings]), sample_csv_import_admin_user_imports_path(address_type: :bill_address), method: :post, data: { confirm: Spree.t(:are_you_sure) }, class: 'btn btn-default' %>
              </div><br>
              <div>
                <%= link_to Spree.t(:import_with_ship_address, scope: [:datashift_import, :import_headings, :user_import_headings]), sample_csv_import_admin_user_imports_path(address_type: :ship_address), method: :post, data: { confirm: Spree.t(:are_you_sure) }, class: 'btn btn-default' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>